Refactoring display of slides in CaseViewer and loading of instances
MGHComputationalPathology/slim pull request #25
Opened 2021-05-31 16:51 UTC by Punzo

@hackermd  Implement https://github.com/MGHComputationalPathology/slim/issues/22, doing the following assumptions:

Tested with https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/pull/54

![image](https://user-images.githubusercontent.com/7985338/120222940-10799b80-c241-11eb-848b-fae9a7c90e96.png)
![image](https://user-images.githubusercontent.com/7985338/120223040-3acb5900-c241-11eb-8ca0-887f5e712d9e.png)

I will continue on https://github.com/MGHComputationalPathology/slim/issues/8 on this draft PR.

2021-06-01 22:18 UTC, hackermd requested changes
This already looks really nice! Great progress @Punzo!

I did a first round of review without delving into all of the implementation details. At this point, I would like to provide some high level comments related to the overall design and terminology:

1. I think we should use the term "acquisition" rather than "slide" (see https://github.com/MGHComputationalPathology/slim/issues/22#issuecomment-852467997 for background).
2. I may be missing something, but I think we could perform the grouping of VL Whole Slide Microscopy Image instances into acquisitions once in the `CaseViewer` component that then pass `acquisition` objects (type is currently called `slideState`) to the other components (the `SlideViewer` and its children).

2021-06-01 22:18 UTC, hackermd commented on src/utils/fromSeriesListToSlideList.tsx
> +    const slideState: dmv.metadata.SlideState = {
Based on our discussion on #22, I think we should refer to this group as an "acquisition".

2021-06-01 22:18 UTC, hackermd commented on src/components/ChannelItem.tsx
> +  description: string,
We may want to describe the "channel" in further detail using information from the Specimen Preparation Sequence (in particular the stain that was used).

@dclunie I assume the items of Specimen Preparation Sequence are structured according to the current version of [TID 8001 Specimen Preparation](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_C.html#sect_TID_8001) and we would need to look for the "Using substance" content item of [TID 8003 Specimen Staining](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_C.html#sect_TID_8003). Is that assumption correct?

2021-06-02 07:38 UTC, Punzo commented on public/config/local.js
> +      url: "http://34.68.90.36/",
thanks for catching this, commited by error!

2021-06-02 08:01 UTC, Punzo commented on types/dicom-microscopy-viewer/index.d.ts
> +
done

2021-06-02 09:20 UTC, Punzo commented on src/components/ChannelItem.tsx
> +  description: string,
done

2021-06-02 09:23 UTC, Punzo commented
> This already looks really nice! Great progress @Punzo!
> 
> I did a first round of review without delving into all of the implementation details. At this point, I would like to provide some high level comments related to the overall design and terminology:
> 
> 1. I think we should use the term "acquisition" rather than "slide" (see [#22 (comment)](https://github.com/MGHComputationalPathology/slim/issues/22#issuecomment-852467997) for background).
> 2. I may be missing something, but I think we could perform the grouping of VL Whole Slide Microscopy Image instances into acquisitions once in the `CaseViewer` component that then pass `acquisition` objects (type is currently called `slideState`) to the other components (the `SlideViewer` and its children).

Thanks for the review! I have applied the comments in https://github.com/MGHComputationalPathology/slim/pull/25/commits/706fe4c61d0deeb06477119a32ae448a343399f5 and replied to https://github.com/MGHComputationalPathology/slim/issues/22#issuecomment-852467997, see https://github.com/MGHComputationalPathology/slim/issues/22#issuecomment-852813751

I will push soon in this same PR the UI upgrade for selecting the bleding parameters for Samples in the case of Multiplexed-Samples

2021-06-02 13:32 UTC, Punzo commented
@hackermd I have finished the UI part with commit https://github.com/MGHComputationalPathology/slim/pull/25/commits/36c31e079739d4e2539cf8ab2397cd97d83984f2

@pieper @fedorov  see a video here:
https://www.dropbox.com/s/ncpawj9yd9idkqt/2021-06-02%2015-25-29.mp4?dl=0

Still to do: finalizing the series/instance grouping with a better logic, i.e. comment https://github.com/MGHComputationalPathology/slim/issues/22#issuecomment-853008049
For this final part I need new or modified datasets since the series/image insatnces of the datasets server http://34.68.90.36/ studyInstanceUID = '1.3.6.1.4.1.5962.99.1.2103930081.1286074986.1595536829665.3.0' has different Frame of reference UID values

2021-06-07 12:50 UTC, Punzo commented
Added proper logic for grouping instances, @hackermd please review. I tested locally (with my local DCM4CHEE) with the new data from David (i.e. https://github.com/MGHComputationalPathology/slim/issues/22#issuecomment-854919111).

2021-06-07 12:53 UTC, Punzo commented
NOTE: at the moment we use `opticalPathIdentifier` to identify channels, in future we should switch to a `opticalPathUID` which will be unique in all cases, see https://github.com/MGHComputationalPathology/slim/issues/22#issuecomment-854642273.

P.S.: `opticalPathUID` does not currently exist in the DICOM standard, we would need to submit a correction.

2021-06-17 21:10 UTC, hackermd requested changes
Thanks @Punzo! It's coming along nicely. I only have a few suggestions for further improving the interface and the structure of the package.

I also noticed a couple of coding style issues and would appreciate if you could fix the linting errors reported by `yarn lint`.

2021-06-17 21:10 UTC, hackermd commented on src/utils/fromSeriesListToSlideList.tsx
> +export const fromSeriesListToSlideList = (
For example, the handling of VOLUME, LABEL, and OVERVIEW metadata could probably be handled in separate functions.

2021-06-17 21:10 UTC, hackermd commented on src/utils/fromSeriesListToSlideList.tsx
> +import {SeriesState, Slide} from './types'
I would suggest renaming this file to `slide.tsx` and define a `Slide` class. The `fromSeriesListToSlideList()` could then become the constructor of the `Slide` class. That would in my opinion result in a cleaner and more intuitive interface.

2021-06-17 21:10 UTC, hackermd commented on src/utils/fromSeriesListToSlideList.tsx
> +        keyOpticalPathIdentifier: '',
I am wondering whether we should already introduce the concept of an Optical Path UID here in the application and rename the property to `opticalPathUID`. Thoughts?

2021-06-17 21:10 UTC, hackermd commented on src/utils/fromSeriesListToSlideList.tsx
> +import {SeriesState, Slide} from './types'
Furthermore, I would suggest moving `slide.tsx` into a separate directory called `data` as a sibling directory of `components`.

2021-06-17 21:13 UTC, hackermd commented
@Punzo I just realized that there were more changes that were not displayed in the `Files changed` tab due to a filter. I will continue the review and may add more comments/suggestions.

2021-06-17 21:21 UTC, hackermd commented on src/utils/types.tsx
> +  Series: dmv.metadata.Series
Is this property still required? Most of the information should also be contained in `volumeMetadata`, `labelMetadata` and `overviewMetadata`.

2021-06-17 21:25 UTC, hackermd commented on src/utils/types.tsx
> +  Series: dmv.metadata.Series
I wonder whether `SeriesState` is required any longer at all? Now that we group image instances into `Slide` instances rather than series, we wouldn't need to pass around the series information, would we?

2021-06-17 21:27 UTC, hackermd commented on src/components/CaseViewer.tsx
> +      seriesList: seriesList,
I wonder whether we need `seriesList`, since all the relevant metadata should also be contained in `slideList`.

2021-06-17 21:29 UTC, hackermd commented on src/components/CaseViewer.tsx
>    handleSeriesSelection (
This should now probably be called `handleSlideSelection`.

2021-06-17 21:34 UTC, hackermd commented on src/components/CaseViewer.tsx
>      /* If a series is encoded in the path, route the viewer to this series.
Hmm...this approach is now problematic, since there may be multiple series. We should consider updating the routing mechanism. The question is what concept (and UID) we could use. There is not really an identifier for the "slide". The closest is probably the Frame of Reference UID. Thoughts?

2021-06-17 21:36 UTC, hackermd commented on src/components/CaseViewer.tsx
> +      slideList: slideList,
I would prefer if we'd call this property just `slides` rather than `slideList`. I used the `List` suffix for certain React components to indicate that they represent HTML lists.

2021-06-17 21:38 UTC, hackermd commented on src/components/SampleItem.tsx
> +  opticalPathSequence: dmv.metadata.OpticalPathDescription,
The use of the term `opticalPathSequence` for the property is very confusing, since it is actually only an individual item.

```suggestion
  opticalPathDescription: dmv.metadata.OpticalPathDescription,
```

2021-06-17 21:40 UTC, hackermd commented on src/components/SampleItem.tsx
> +  itemRemoveHandler: SamplesList["handleItemRemoveSample"]
Is this valid Typescript? Either way, I would prefer type annotating the function signature explicitly.

2021-06-17 22:16 UTC, hackermd commented on src/components/SampleItem.tsx
> +    value: number[],
```suggestion
    values: number[],
```

2021-06-17 22:42 UTC, hackermd requested changes

2021-06-17 22:42 UTC, hackermd commented on src/components/SampleItem.tsx
> +    value: number[],
```suggestion
    values: number[],
```

2021-06-17 22:42 UTC, hackermd commented on src/components/SampleItem.tsx
> +      (identifier) as dmv.viewer.BlendingInformation
`BlendingInformation` is not defined under the `viewer` namespace, but under the `metadata` namespace (see [dicom-microscopy-viewer](BlendingInformation). This should be correctly reflected here.

2021-06-17 22:42 UTC, hackermd commented on src/components/SampleItem.tsx
> +      (identifier) as dmv.viewer.BlendingInformation
It should actually go under the `channel` namespace rather than the `metadata` namespace. I would suggest changing it at this point, where probably nobody else is using this functionality..

2021-06-17 22:42 UTC, hackermd commented on src/components/SampleItem.tsx
> +  specimenDescriptionSequence: dmv.metadata.SpecimenDescription,
See comment above:

```suggestion
  specimenDescription: dmv.metadata.SpecimenDescription,
```

2021-06-17 22:42 UTC, hackermd commented on src/components/SampleItem.tsx
> +          name: 'Description',
Better be explicit here, since it may otherwise not be clear what is being described:

```suggestion
          name: 'Specimen Description',
```

2021-06-17 22:42 UTC, hackermd commented on src/components/SampleItem.tsx
> +    )
This looks like it's copied from `SpecimenItem`. I would not repeat all the information about surgical collection, fixative, and embedding. That should be shared across samples.

I would suggest showing information of all preparation steps but "staining" in `SpecimenItem` and only show the information of "staining" in `SampleItem`. In case of a color image, I would continue to show information of all preparation steps in `SpecimenItem`.

Moving forward, we may want to compute the diff across samples, and then show all common preparation steps in `SpecimenItem` and the variable preparations steps for the corresponding `SampleItem`. However, I would wait until we have standardized the encoding of specimen preparation for multiplexed IF (cc @dclunie for awareness).

2021-06-17 22:42 UTC, hackermd commented on src/components/SampleItem.tsx
> +            <Button type="primary" danger icon={<CloseSquareFilled />} onClick={this.handleRemoveSample}>
Instead of using a separate button, could we use a [clickable Batch](https://ant.design/components/badge/#components-badge-demo-link) and an `x` icon?

2021-06-17 22:42 UTC, hackermd commented on src/components/SamplesList.tsx
> +            key={item.OpticalPathSequence[0].OpticalPathIdentifier}
This may get us into trouble. See comment on introducing an Optical Path UID property.

2021-06-22 10:31 UTC, Punzo commented on src/utils/fromSeriesListToSlideList.tsx
> +        keyOpticalPathIdentifier: '',
`keyOpticalPathIdentifier` is the Optical Path identifier that will be used to identify the first channel to be loaded and visualized when opening a study with "multi channels".

Note that if initiallySelectedSeriesInstanceUID is provided, than the keyOpticalPathIdentifier will be teh one of the first "channel" identified in the series.

No I don't think we should use `opticalPathUID`. This because at the moment we don't have any unique dicom attribute that identify a channel. OpticalPathIdentifier attribute is the best shot and we currently use it. Thefore using another  variable name will be just very confusing. Of course as soon as we have an opticalPathUID attribute (fully unique) in the standard we can switch to use that one.

2021-06-22 10:53 UTC, Punzo commented on src/utils/fromSeriesListToSlideList.tsx
> +        slide.description = 'Multiplexed-Samples'
We still a string in some cases. For example all the test data on multi channel have no label/overview instances. Therefore we need at least a string in description as `Multiplexed-Samples`. I suggest to simply put always this string and it would be simply `Multiplexed-Samples` for monochorme multi channels, `RGB Slide` for a RGB image and `Monochorme Slide` for a monochorme image

2021-06-22 11:25 UTC, Punzo commented on src/utils/types.tsx
> +  Series: dmv.metadata.Series
we still need them, because for the url redirection we use the series uid. How it works, it is that I store all the series uid in the slide (`seriesUIDs` variable in the slide interface). Then when the url is opened with a series uid, we look in the list of series uid in the slides and we show the slide that has the series uid selected in its seriesUIDs list.

2021-06-22 11:30 UTC, Punzo commented on src/components/CaseViewer.tsx
> +      seriesList: seriesList,
we still need them only for the redirection of the url, which is based on series UIDs, see also https://github.com/MGHComputationalPathology/slim/pull/25#discussion_r656126006. Of course if we change the redirection from `/studies/${this.props.studyInstanceUID}/series/${seriesInstanceUID}` to something else we could eliminate all the storing of the seriesList. However, I would leave as it is, because at the moment we don't have an unique UID to use to identify slides and it would be very confunsing for the users to use the Optical Path Identifier.

2021-06-22 11:32 UTC, Punzo commented on src/components/CaseViewer.tsx
>    handleSeriesSelection (
I think is is better to still name it `handleSeriesSelection`, this because we don't have an unique UID to select slides. At teh momement we actually select series and then teh software choose to which slide is related the series (slide stores all the series UIDs) see also previous comments https://github.com/MGHComputationalPathology/slim/pull/25#discussion_r656129187 and https://github.com/MGHComputationalPathology/slim/pull/25#discussion_r656126006

2021-06-22 11:35 UTC, Punzo commented on src/components/CaseViewer.tsx
>      /* If a series is encoded in the path, route the viewer to this series.
as I wrote in the previous comments, yes we still redirect using seriesUIDs which do not identify slides. Probably Frame of Reference UID is good enough, but I would wait to have the OpitcalPathUID in the DICOM standard as you suggested. That would be unique, straightforward and it would not create confusion.

2021-06-22 11:36 UTC, Punzo commented on src/components/CaseViewer.tsx
> +      slideList: slideList,
called them slideArray, since slides is the name of the new class that handle series information to slides.

2021-06-22 11:57 UTC, Punzo commented on src/components/SamplesList.tsx
> +            key={item.OpticalPathSequence[0].OpticalPathIdentifier}
I agree with you, but unitl we don't have Optical Path UID property in teh standard the OpticalPathIdentifier is the best shot. This is alreaby been tracked in https://github.com/MGHComputationalPathology/slim/issues/31

2021-06-22 13:15 UTC, Punzo commented on src/components/SampleItem.tsx
> +            <Button type="primary" danger icon={<CloseSquareFilled />} onClick={this.handleRemoveSample}>
unfortunately ant-badge do not have onClick events (you can just put clickable links into them).

Another option can be to use a [popconfirm](https://ant.design/components/popconfirm/) when clicking on the card descriptions, but I think that the simple X button is much more intuitive.

2021-06-22 13:28 UTC, Punzo commented
@hackermd I have replied/applied to your commets.

TO DO:
1) there is still a main point unresolved: rerouting. At the moment is done with `seriesUID` in the url. I think we should updated this logic later on when we will have the `OpticalPathUID` in the standards since at the moment we don't have any real unique UID to identify `Slides`. 

In the current implementation all the seriesUIDs that "contribute" to the Slide are stored in the slide interface and when rerouting it is picked the Slide that have the selected seriesUID in its seriesUIDs list. 


See comments: 
https://github.com/MGHComputationalPathology/slim/pull/25#discussion_r656126006 https://github.com/MGHComputationalPathology/slim/pull/25#discussion_r656129187 https://github.com/MGHComputationalPathology/slim/pull/25#discussion_r656130849 https://github.com/MGHComputationalPathology/slim/pull/25#discussion_r656132891

2) release new version of https://github.com/MGHComputationalPathology/dicom-microscopy-viewer and update in SLIM the package.json.

2021-06-22 15:08 UTC, hackermd commented on src/components/SamplesList.tsx
> +            key={item.OpticalPathSequence[0].OpticalPathIdentifier}
I tend argue that we need to assign an Optical Path UID, independent of whether it will be included in the standard. For now, the UID may be assigned dynamically and not persisted. We cannot rely on Optical Path Identifier, since it's not guaranteed to be unique.

2021-06-22 18:22 UTC, dclunie commented on src/components/SamplesList.tsx
> +            key={item.OpticalPathSequence[0].OpticalPathIdentifier}
If FrameOfReferenceUID and OpticalPathIdentifier together produce a combination that is unique within a StudyInstanceUID, would that not suffice?

2021-06-22 19:11 UTC, hackermd commented
Thanks @Punzo.

> there is still a main point unresolved: rerouting. At the moment is done with seriesUID in the url. I think we should updated this logic later on when we will have the OpticalPathUID in the standards since at the moment we don't have any real unique UID to identify Slides

I don't think the Optical Path UID would help us here. The problem we are facing is due to the fact that we are blending images that are contained in different [Series](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/chapter_A.html#sect_A.1.2.3). Per definition, the collection of images that belong to a "slide" share the same [Frame of Reference](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/chapter_A.html#sect_A.1.2.5), so we could use the Frame of Reference UID for routing. However, the Frame of Reference is not a child of the [Study](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/chapter_A.html#sect_A.1.2.2) in the [IOD Entity-Relationship Model](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/chapter_A.html#figure_A.1-1) and other images that are not part of the collection (and should thus not be blended) may have the same Frame of Reference UID. Therefore, we can't use the Frame of Reference UID either.

In conclusion, I tend argue that we should stick to using the Series Instance UID for routing and route each "series" that is part of a "slide" (collection of images with the same Frame of Reference UID and Container Identifier) to the corresponding `SlideViewer` instance. Ideally, the viewer would then also display the images (channel/sample) that are contained in the specified series (specified via the Series Instance UID in the URL).

2021-06-23 12:10 UTC, hackermd commented on public/config/local.js
> +      url: "http://34.68.90.36/",
Could you please change it back to localhost?

2021-06-23 12:10 UTC, hackermd commented on src/components/SamplesList.tsx
> +            key={item.OpticalPathSequence[0].OpticalPathIdentifier}
> If FrameOfReferenceUID and OpticalPathIdentifier together produce a combination that is unique within a StudyInstanceUID, would that not suffice?

@dclunie I don't think that the combination would result in a unique value for each "channel"/"sample" either.

2021-06-23 12:31 UTC, Punzo commented on public/config/local.js
> +      url: "http://34.68.90.36/",
sorry I always forget to change them back after testing, done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/d39920423617f81050bfaa213a7e35226ea46931

2021-06-23 12:40 UTC, Punzo commented on src/components/SamplesList.tsx
> +            key={item.OpticalPathSequence[0].OpticalPathIdentifier}
also having two parameters will make the interface with the dicom-microscopy-viewer much more complicated. 

P.S.: in general dicom-microscopy-viewer is currently using as well the Optical Path Identifier to identify channels. 

> We cannot rely on Optical Path Identifier, since it's not guaranteed to be unique.

again I see your point, but in dicom-microscopy-viewer we are using the Optical Path Identifier ( and we have to use the same parameter to access channels both in SLIM and dicom-microscopy-viewer, otherwise teh two will be poiting to two different things). 

I would say that we know it is not unique and we are tracking it in https://github.com/MGHComputationalPathology/slim/issues/31 and as soon as we have a better solution we can update the code both in dicom-microscopy-viewer and SLIM.

2021-06-23 12:44 UTC, Punzo commented
> In conclusion, I tend argue that we should stick to using the Series Instance UID for routing and route each "series" that is part of a "slide" (collection of images with the same Frame of Reference UID and Container Identifier) to the corresponding `SlideViewer` instance. Ideally, the viewer would then also display the images (channel/sample) that are contained in the specified series (specified via the Series Instance UID in the URL).

I agree, at the moment it is already managed that when selecting a series in the url, the viewr will display the right slide that contains the instances from that series. So I think we are good to go on this.

2021-06-23 13:51 UTC, Punzo commented
> I also noticed a couple of coding style issues and would appreciate if you could fix the linting errors reported by `yarn lint`.

done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/89b2ea4a2905d6de7f99fdb36109e201674b4248

2021-06-23 13:59 UTC, hackermd requested changes

2021-06-23 13:59 UTC, hackermd commented on src/components/SlideList.tsx
> +    selectedSeriesInstanceUID: '',
I would use `undefined` instead of an empty string. An empty string is not a valid DICOM UID

2021-06-23 13:59 UTC, hackermd commented on src/components/SlideList.tsx
> +      />
```suggestion
      const slideItem = (
        <SlideItem
          key={slide.key}
          slide={slide}
        client={this.props.client}
        />
      )
```

2021-06-23 13:59 UTC, hackermd commented on src/components/SlideList.tsx
> +      };
Why would we add an "empty" slide?

2021-06-23 13:59 UTC, hackermd commented on src/components/CaseViewer.tsx
> +  slideArray: Slide[]
```suggestion
  slides: Slide[]
```

2021-06-23 13:59 UTC, hackermd commented on src/data/slides.tsx
> +class Slides {
You currently use the `Slides` class as follows:

```javascript
const slides = new Slides(seriesArray, selectedSeriesInstanceUID)
const slideArray = slides.getSlideArray()
```

This could just become

```javascript
const slides = createSlides(seriesArray, selectedSeriesInstanceUID)
```

or something along those lines

2021-06-23 13:59 UTC, hackermd commented on src/components/CaseViewer.tsx
> +        if (instance.ImageType !== undefined &&
Why would `ImageType` be `undefined`? This is a type 1 attribute

2021-06-24 06:21 UTC, Punzo commented on src/components/CaseViewer.tsx
> +      const seriesMetadata = firstSeriesState.Series as dmv.metadata.Series
this is already done, if in the url path is provided the series UID, then CaseViewer will display the slide correspondent to that series. the first series is used only if the series string is missing in the url (i.e. when the user simply open the study by clicking on the UI item of the study list at the beginning). I think this is teh right behaviour, i.e. here is simply taking the first series if it was not specified.

2021-06-24 06:26 UTC, Punzo commented on src/components/SlideList.tsx
> +    selectedSeriesInstanceUID: '',
that property is declared as `string`, therefore `undefined` is not an accepted value. We would need to declare it as `any`, but I would avoid using `any` declaration.

2021-06-24 06:27 UTC, Punzo commented on src/components/SlideList.tsx
> +      />
solved in https://github.com/MGHComputationalPathology/slim/pull/25/commits/89b2ea4a2905d6de7f99fdb36109e201674b4248

2021-06-24 06:31 UTC, Punzo commented on src/components/SlideList.tsx
> +      };
all this if condition is not needed, not sure why I have added it. I just removed it in https://github.com/MGHComputationalPathology/slim/pull/25/commits/97fa8eae7736b345d8206d8f836006923799dd59

2021-06-24 06:34 UTC, Punzo commented on src/components/CaseViewer.tsx
> +        if (instance.ImageType !== undefined &&
It was defined in the metadata types as optional, fixed in https://github.com/MGHComputationalPathology/slim/pull/25/commits/b354a6cd397825c40cecfb13ad2d382b9334a36f

2021-06-24 07:41 UTC, Punzo commented on src/components/SampleItem.tsx
> +            <Button type="primary" danger icon={<CloseSquareFilled />} onClick={this.handleRemoveSample}>
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/e0b698a2a58d9bbbec07aded39fdf8be76586df1

2021-06-24 08:02 UTC, Punzo commented on src/data/slides.tsx
> +class Slides {
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/13a6c2cc0f5a262ff9878e372771b33d6c5a6143

2021-06-24 08:03 UTC, Punzo commented on src/components/CaseViewer.tsx
> +  slideArray: Slide[]
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/13a6c2cc0f5a262ff9878e372771b33d6c5a6143

2021-06-24 08:31 UTC, Punzo commented on src/components/CaseViewer.tsx
> +  seriesArray: SeriesState[]
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/1244c8290b14be177b88c26c1f696b31bba54a5c

2021-06-24 08:32 UTC, Punzo commented on src/components/CaseViewer.tsx
> +      seriesList: seriesList,
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/1244c8290b14be177b88c26c1f696b31bba54a5c

2021-06-24 08:32 UTC, Punzo commented on src/utils/types.tsx
> +  Series: dmv.metadata.Series
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/1244c8290b14be177b88c26c1f696b31bba54a5c

2021-06-24 08:35 UTC, Punzo commented
@hackermd I have applied the last review. Please have a look, thanks!

2021-06-24 13:57 UTC, hackermd requested changes

2021-06-24 13:57 UTC, hackermd commented on src/components/SamplesList.tsx
> +            key={item.OpticalPathSequence[0].OpticalPathIdentifier}
I would like to address this sooner rather than later, since this will result in a backwards incompatible change that will break the API of the dicom-microscopy-viewer library.

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideItem.tsx
>    containerIdentifier: string
Why is `containerIdentifier` in `state`? This is not supposed to change. The information is available on `props.slide`. One should be able to just access it via `this.props.slide.overviewMetadata[0].ContainerIdentifier`.

```suggestion
```

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideItem.tsx
>    containerIdentifier: string
If you want a separate property, then I would recommend either a [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) or a private attribute.

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideList.tsx
> +    }))
Why do you set `this.props.initiallySelectedSeriesInstanceUID` on the state in `componentDidMount` rather than the constructor? This is generally not a good idea (see [React docs](https://reactjs.org/docs/react-component.html#componentdidmount)).

> You may call setState() immediately in componentDidMount(). It will trigger an extra rendering, but it will happen before the browser updates the screen. This guarantees that even though the render() will be called twice in this case, the user won’t see the intermediate state. Use this pattern with caution because it often causes performance issues. In most cases, you should be able to assign the initial state in the constructor() instead.

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideViewer.tsx
>    metadata: dmv.metadata.VLWholeSlideMicroscopyImage[]
That information is also available on `activeSlide`, isn't it? I would avoid having two separate state properties that both need to stay in sync. It is error prone. This may be a use case for a getter.

```suggestion
```

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideViewer.tsx
> +    activeSlide: this.slide,
Why do we need `this.slide` and `this.state.activeSlide`? I would suggest removing the `slide` attribute from the class and tracking the currently active slide via state.

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideViewer.tsx
> +
I consider such objects with "nullable" values highly problematic. It would be much cleaner to just have an `undefined`. In this case, I don't think we actually need the attribute.

```suggestion
```

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideViewer.tsx
> +        activeSlide: slide,
This should probably go into the constructor, i.e., the default `activeSlide` should be set upon construction.

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideViewer.tsx
>        this.setState((state) => ({ metadata: series }))
Could we handle this outside of this component such that `slide.volumeMetadata` is already formatted correctly?

2021-06-24 13:57 UTC, hackermd commented on src/components/SlideViewer.tsx
>        this.setState((state) => ({ metadata: series }))
See also comment on the need for storing `metadata` on the state object.

2021-06-24 13:57 UTC, hackermd commented on src/data/slides.tsx
> +}
There shouldn't be any default values. This will only get us into trouble. Whoever creates the `Slide` objects will be responsible for populating the required information.

2021-06-24 13:57 UTC, hackermd commented on src/data/slides.tsx
> +  initiallySelectedSeriesInstanceUID: string = ''
Please use `undefined` instead of a `''`:

```suggestion
  initiallySelectedSeriesInstanceUID?: string
```

2021-06-24 13:57 UTC, hackermd commented on src/utils/types.tsx
> +export interface InstancesMetadata {
Is that really something that we will need to re-use? If so, I would define it in `slide.tsx`.

2021-06-24 13:57 UTC, hackermd commented on src/data/slides.tsx
> +  slide: Slide
I would suggest passing the relevant attributes directly

```suggestion
  frameOfReferenceUID: string,
  containerIdentifier: string
```

Same for the other functions.

2021-06-24 13:57 UTC, hackermd commented on src/data/slides.tsx
> +      parseOverviewMetadataFromListToSlide(instancesMetadata.overviewMetadata, slide)
I am wondering whether these should be private methods on the `Slide` class. The constructor of the `Slide` class could accept the `instancesMetadata`, parse and extract the relevant information, and populate the attributes on the `Slide` object.

2021-06-24 13:57 UTC, hackermd commented on src/data/slides.tsx
> +    }
This could probably be factored into a separate function/method which determines whether a given metadata object belongs to the slide.

2021-06-29 07:04 UTC, Punzo commented on src/components/SamplesList.tsx
> +            value={this.state.selectedOpticalPathIdentifier} allowClear
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/e39270e2fb5421d964b9a4de310deb1546b9c9fe

2021-06-29 07:05 UTC, Punzo commented on src/components/SamplesList.tsx
> +    selectedOpticalPathIdentifier: ''
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/e39270e2fb5421d964b9a4de310deb1546b9c9fe

2021-06-29 07:05 UTC, Punzo commented on src/components/SamplesList.tsx
> +      selectedOpticalPathIdentifier: ''
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/e39270e2fb5421d964b9a4de310deb1546b9c9fe

2021-06-29 07:24 UTC, Punzo commented on src/components/SlideItem.tsx
>    containerIdentifier: string
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/a51c9c79710a08163143cb6bc485c90f91bd998c

2021-06-29 07:29 UTC, Punzo commented on src/components/SlideList.tsx
> +    }))
done https://github.com/MGHComputationalPathology/slim/pull/25/commits/9122bd397bcd3bc3f8078c0a521695b65c249255

2021-06-29 09:50 UTC, Punzo commented on src/components/SlideViewer.tsx
>    metadata: dmv.metadata.VLWholeSlideMicroscopyImage[]
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/2b480cc755be204481548d3397dd1a94d2cdd585

2021-06-29 09:58 UTC, Punzo commented on src/components/SlideViewer.tsx
> +    activeSlide: this.slide,
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/13e8f42278f4c3473105c364d904edc4e688dbbc

2021-06-29 10:00 UTC, Punzo commented on src/components/SlideViewer.tsx
>        this.setState((state) => ({ metadata: series }))
these lines are not necessary anumore, see https://github.com/MGHComputationalPathology/slim/commit/2b480cc755be204481548d3397dd1a94d2cdd585

2021-06-29 10:28 UTC, Punzo commented on src/components/SlideViewer.tsx
> +
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/11f602ac3fcd6884fccb671852d8769b093b8d75

2021-06-29 10:29 UTC, Punzo commented on src/components/SlideViewer.tsx
> +        activeSlide: slide,
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/11f602ac3fcd6884fccb671852d8769b093b8d75

2021-06-29 11:57 UTC, Punzo commented on src/data/slides.tsx
> +}
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/b457fc27cee8440c76bb315a09b78f4b05a20732

2021-06-29 11:57 UTC, Punzo commented on src/data/slides.tsx
> +  initiallySelectedSeriesInstanceUID: string = ''
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/b457fc27cee8440c76bb315a09b78f4b05a20732

2021-06-29 11:59 UTC, Punzo commented on src/utils/types.tsx
> +export interface InstancesMetadata {
it is necessary in passing the series array to slides trough the fetch functions. moved the declaration in slide.tsx https://github.com/MGHComputationalPathology/slim/pull/25/commits/b457fc27cee8440c76bb315a09b78f4b05a20732

2021-06-29 11:59 UTC, Punzo commented on src/data/slides.tsx
> +  slide: Slide
done https://github.com/MGHComputationalPathology/slim/pull/25/commits/b457fc27cee8440c76bb315a09b78f4b05a20732

2021-06-29 11:59 UTC, Punzo commented on src/data/slides.tsx
> +      parseOverviewMetadataFromListToSlide(instancesMetadata.overviewMetadata, slide)
done https://github.com/MGHComputationalPathology/slim/pull/25/commits/b457fc27cee8440c76bb315a09b78f4b05a20732

2021-06-29 11:59 UTC, Punzo commented on src/data/slides.tsx
> +    }
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/b457fc27cee8440c76bb315a09b78f4b05a20732

2021-06-29 12:01 UTC, Punzo commented
@hackermd thanks again for your last review, I applied the comments. We need only to address the non uniqueness of the Optical Path Identifier parameter.

2021-07-08 12:33 UTC, hackermd commented on src/components/SlideList.tsx
> +    selectedSeriesInstanceUID: '',
Please use `selectedSeriesInstanceUID?: string` to indicate that the value may be `undefined`. This is explicit and idiomatic TypeScript.

2021-07-08 12:37 UTC, hackermd commented on src/utils/fromSeriesListToSlideList.tsx
> +        keyOpticalPathIdentifier: '',
We will need a `opticalPathUID` anyways. Naming the property `keyOpticalPathIdentifier` is more confusing in my opinion.

I would suggest using `opticalPathUID` internally within the app and in parallel working with @dclunie on including the attribute standard.

2021-07-08 16:11 UTC, hackermd commented on src/components/SamplesList.tsx
> +            key={item.OpticalPathSequence[0].OpticalPathIdentifier}
Based on our conversation from this morning, we'll continue assuming that the Optical Path Identifier will be unique.

@Punzo no change will be required in the application or the dicom-microscopy-viewer library. I will resolve this comment and other related comments.

@dclunie it would be great if we could improve the language in the standard. Maybe we could add an additional note to clarify how the attribute is intended to be used in the context of multiplexed immunofluorescence imaging and to which extent values should be unique to enable particular use cases.

2021-07-08 16:17 UTC, hackermd commented on src/components/SamplesList.tsx
> +                      item.OpticalPathSequence[0].OpticalPathIdentifier
We will continue to use Optical Path Identifier and assume that values are unique. Rather than adding a new Optical Path UID attribute to the standard, we will explore possibilities to further clarify uniqueness of expectations/requirements by receiving applications. See also [this comment](https://github.com/MGHComputationalPathology/slim/pull/25/files#r657055257).

2021-07-08 16:26 UTC, hackermd commented on src/utils/fromSeriesListToSlideList.tsx
> +        keyOpticalPathIdentifier: '',
I think I misunderstood the intended use of `keyOpticalPathidentifier`. The term is a bit confusing. What do you think about calling it `selectedOpticalPathidentifier`? There are several existing properties in the app named `selected*` so that would be consistent.

In addition, I would suggest renaming `key` to `selectedSeriesUID` for consistency and improved clarity.

2021-07-08 16:35 UTC, hackermd commented on src/components/CaseViewer.tsx
> +    let selectedSeriesInstanceUID = ''
```suggestion
    let selectedSeriesInstanceUID = undefined
```

See [this comment](https://github.com/MGHComputationalPathology/slim/pull/25#discussion_r666149795)

2021-07-08 16:35 UTC, hackermd commented on src/components/SlideList.tsx
> +    selectedSeriesInstanceUID: '',
Somehow the logic doesn't seem to fit yet. The value of the `selectedSeriesInstanceUID` should ultimately neither be `undefined`. However, that is currently only guaranteed because the value is set to `""` (empty string) at some point. The TypeScript therefore doesn't complain, but it would probably still break the app if no series has been selected.

2021-07-08 16:37 UTC, hackermd commented on src/components/CaseViewer.tsx
> +    let selectedSeriesInstanceUID = ''
This would allow the TypeScript compiler to catch the problem. Setting the value to an empty string will just propagate the problem.

2021-07-08 16:39 UTC, hackermd requested changes
With the main issue regarding the Optical Path Identifier resolved, there are only two small minor comments remaining. The first is related to naming things and the second to type declarations and nullable values. Almost there :)

2021-07-15 08:07 UTC, Punzo commented on src/utils/fromSeriesListToSlideList.tsx
> +        keyOpticalPathIdentifier: '',
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/9fe0a311e6aa9ed196267ddfd880536d5043a4e9

2021-07-15 08:17 UTC, Punzo commented on src/components/SlideList.tsx
> +    selectedSeriesInstanceUID: '',
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/c80070ff1342f92a08c9c8bd5806ced64c901de0

2021-07-15 08:20 UTC, Punzo commented on src/components/CaseViewer.tsx
> +    let selectedSeriesInstanceUID = ''
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/1fba907d84eddde77ccd787686a243b3af4061a2

2021-07-15 08:22 UTC, Punzo commented
> With the main issue regarding the Optical Path Identifier resolved, there are only two small minor comments remaining. The first is related to naming things and the second to type declarations and nullable values. Almost there :)

Hi @hackermd I have applied your comments, thanks for the review! please have a look if we can merge.

Next steps To Do:
1) make a new release of https://github.com/MGHComputationalPathology/dicom-microscopy-viewer
2) update the package.json
3) make new release of slim

2021-07-15 15:03 UTC, hackermd reviewed
Thanks @Punzo! Should I go ahead and perform final review and testing or are you still going to make further commits?

2021-07-15 15:09 UTC, Punzo commented
> Thanks @Punzo! Should I go ahead and perform final review and testing or are you still going to make further commits?

I have finished, please go ahead!

2021-07-22 14:55 UTC, Punzo commented
@igoroctaviano do you know why the Firebase deploy is skipped? I tried to create a new PR (https://github.com/MGHComputationalPathology/slim/pull/41) and I had the same issue.

2021-07-22 19:34 UTC, hackermd requested changes
Unfortunately, I ran into several issues/bugs when testing locally. See individual comments for details.

One of the reasons these bugs have remained undetected could be the liberal use of optional properties (i.e., properties whose values may be `undefined`). I would avoid that whenever possible, because it generally leads to undefined propagation, which can cause nasty bugs downstream that are difficult to detect and fix. Please revisit the type annotations of properties that you changed or introduced.

I further noticed that the `config/local.js` has changed. Please revert the local configuration to 

```javascript
window.config = {
    servers: [
    {
      id: "local",
      url: "http://localhost:8008/dicomweb",
      write: true
    }
  ],
  ...
}
```

2021-07-22 19:34 UTC, hackermd commented on src/components/CaseViewer.tsx
>      } else {
This is no done twice in the same component. We should probably factor that out.

2021-07-22 22:05 UTC, Punzo commented on src/data/slides.tsx
> +        this.overviewMetadata.push(metadata)
in https://github.com/MGHComputationalPathology/slim/pull/25/commits/384f3ead3b74de294b1a2064d5ca32ac878244dc I have changed the names of the methods and added few lines of descriptions in the docstring. 

I disagree in moving the `Slide` methods (`addInstanceMetadata`, `addLabelInstanceMetadata`, `addVolumeInstanceMetadata`, `addOverviewInstanceMetadata`) in separate functions. It would just overcomplicate the logic with no substancial advantage. I would say, it goes against a straightforward object oriented programming (since these methods/function needs to change several private attributes of the objects `Slide`). For example if you separate these methods from the Slide class in private functions, you would need then to pass the slide objects to the functions and then the functions would anyway to modify the 'state' of the object. Also to be noted is that `addLabelInstanceMetadata`, `addVolumeInstanceMetadata`, `addOverviewInstanceMetadata` are already private methods.

2021-07-22 22:05 UTC, Punzo commented on src/data/slides.tsx
> +  private instanceBelongToSlide (
done in https://github.com/MGHComputationalPathology/slim/commit/384f3ead3b74de294b1a2064d5ca32ac878244dc

2021-07-22 22:18 UTC, Punzo commented on src/components/CaseViewer.tsx
> +    { seriesInstanceUID }: { seriesInstanceUID?: string }
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/6e2bf8f9ccabed9c59383f8657401f71cb150588

2021-07-22 22:18 UTC, Punzo commented on src/components/CaseViewer.tsx
> +      console.warn('switching series: seriesInstanceUID not found.')
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/6e2bf8f9ccabed9c59383f8657401f71cb150588

2021-07-22 22:18 UTC, Punzo commented on src/components/SlideList.tsx
> +  initiallySelectedSeriesInstanceUID?: string
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/6e2bf8f9ccabed9c59383f8657401f71cb150588

2021-07-22 22:19 UTC, Punzo commented on src/components/CaseViewer.tsx
>      } else {
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/6e2bf8f9ccabed9c59383f8657401f71cb150588

2021-07-22 22:25 UTC, Punzo commented on src/components/CaseViewer.tsx
> +      selectedSeriesInstanceUID = firstVolumeSeriesIstance.SeriesInstanceUID
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/25f7e58df55d0a81da56b86661abbfb8d9264f96

2021-07-22 22:25 UTC, Punzo commented on src/components/CaseViewer.tsx
> +      dmv.metadata.formatMetadata(firstSlide.volumeMetadata[0]) as dmv.metadata.Study
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/25f7e58df55d0a81da56b86661abbfb8d9264f96

2021-07-22 23:08 UTC, Punzo commented on src/components/CaseViewer.tsx
> +        `/studies/${this.props.studyInstanceUID}/series/${seriesInstanceUID}`
fixed in https://github.com/MGHComputationalPathology/slim/pull/25/commits/9d6abac55191060390a6dc3f95e5d3af67b8fb5d. Please note also that this fix is needed too: https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/pull/56

(tested with study 2.25.261030824872518877931236952174606351723  in https://idc-external-006.uc.r.appspot.com

2021-07-22 23:11 UTC, Punzo commented
> Unfortunately, I ran into several issues/bugs when testing locally. See individual comments for details.
> 
> One of the reasons these bugs have remained undetected could be the liberal use of optional properties (i.e., properties whose values may be `undefined`). I would avoid that whenever possible, because it generally leads to undefined propagation, which can cause nasty bugs downstream that are difficult to detect and fix. Please revisit the type annotations of properties that you changed or introduced.
> 
> I further noticed that the `config/local.js` has changed. Please revert the local configuration to
> 
> ```js
> window.config = {
>     servers: [
>     {
>       id: "local",
>       url: "http://localhost:8008/dicomweb",
>       write: true
>     }
>   ],
>   ...
> }
> ```

Hi @hackermd tahnsk for the review. I have fixed the main issue regarding the undefined variables. Please note that also this fix is needed https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/pull/56. Regarding  `url: "http://localhost:8008/dicomweb" ` I just used the one in the current master which is set to `url: "https://idc-external-006.uc.r.appspot.com",`.

2021-07-22 23:31 UTC, Punzo commented
> Unfortunately, I ran into several issues/bugs when testing locally. See individual comments for details.
> 
> One of the reasons these bugs have remained undetected could be the liberal use of optional properties (i.e., properties whose values may be `undefined`). I would avoid that whenever possible, because it generally leads to undefined propagation, which can cause nasty bugs downstream that are difficult to detect and fix. Please revisit the type annotations of properties that you changed or introduced.
> 
> I further noticed that the `config/local.js` has changed. Please revert the local configuration to
> 
> ```js
> window.config = {
>     servers: [
>     {
>       id: "local",
>       url: "http://localhost:8008/dicomweb",
>       write: true
>     }
>   ],
>   ...
> }
> ```

Hi @hackermd thanks for the review.

I have fixed the main issue regarding the undefined variables. 

Please also note that this fix is needed as well: https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/pull/56. 

Regarding the modification of `config/local.js`  (`url: "http://localhost:8008/dicomweb" ` into `url: "https://idc-external-006.uc.r.appspot.com",`), I just used the one in the current master which is set to `url: "https://idc-external-006.uc.r.appspot.com",`. Anywa, I switched back to the `url: "http://localhost:8008/dicomweb" `

2021-07-23 12:57 UTC, hackermd commented on src/data/slides.tsx
> +        this.overviewMetadata.push(metadata)
All these methods do is parse the metadata and then set values on the appropriate attributes on the `Slide` object. To me, this should either be the responsibility of the `Slide` constructor or the `createSlides()` factory function. I would prefer the latter as it would allow us to make `Slide` objects immutable (or least not provide methods for mutating an object after construction). The `Slide` objects determine a lot of downstream application behavior and I think we'll do us a big favor in making them immutable.

I would define a `SlideOptions` interface based on the attributes of `Slide` (`containerIdentifier`, `selectedSeriesUID`, etc.), create these option objects in `createSlides` using `_addInstanceMetadata()`, and then pass one object to the constructor of `Slide` for each "detected" slide. 

```typescript
interface SlideOptions {
  frameofReferenceUID: string
  containerIdentifier: string
  areImagesMonochrome: boolean
  isMultiplexedSamples: boolean
  selectedSeriesUID: string
  seriesUIDsList: string[] = []
  selectedOpticalPathidentifier: string
  opticalPathIdentifiersList: string[] = []
  description?: string
  volumeMetadata: VLWholeSlideMicroscopyImage[]
  labelMetadata: VLWholeSlideMicroscopyImage[] = []
  overviewMetadata: VLWholeSlideMicroscopyImage[] = []
}
```

None of the attributes required by the standard (`frameOfReferenceUID`, `containerIdentifier`, `volumeMetadata`, etc.) shall be optional, i.e, their values shall never be `undefined` or `[]`.

We can then add getter methods to the `Slide` class to make the properties read only.

2021-07-23 13:03 UTC, hackermd commented
> Regarding the modification of config/local.js (url: "http://localhost:8008/dicomweb" into url: "https://idc-external-006.uc.r.appspot.com",), I just used the one in the current master which is set to url: "https://idc-external-006.uc.r.appspot.com",. Anyway, I switched back to the url: "http://localhost:8008/dicomweb" 

Thanks! Sorry, it seems I missed this on another PR.

2021-07-23 13:04 UTC, hackermd commented
> Please also note that this fix is needed as well: MGHComputationalPathology/dicom-microscopy-viewer#56.

Thanks! I approved and merged this PR already. Will draft a new release once this PR is finalized.

2021-07-23 13:10 UTC, hackermd commented
> I have fixed the main issue regarding the undefined variables (nice catch!!! I previously tested only studies with a multichannels slide or 1 RGB slide).

Great! Let's briefly go through all optional parameters and double-check whether they should indeed be optional. For example, the `selectedSeriesInstanceUID` property on the `Slide` class is optional, but the application won't function properly if that property is not set. Same applies to `containerIdentifier`, which represents a type 1 DICOM attribute that is  guaranteed to be present in any VL Whole Sllide Microscopy Image instance. If the value cannot be determined upon construction of the `Slide` object, the application should just fail immediately and gracefully, rather than propagating the issue through the app.

2021-07-26 09:24 UTC, Punzo commented on src/data/slides.tsx
> +        this.overviewMetadata.push(metadata)
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/3a14700fadc8dd2ec993d897362a0af8e0770b06

2021-07-26 09:24 UTC, Punzo commented
> > I have fixed the main issue regarding the undefined variables (nice catch!!! I previously tested only studies with a multichannels slide or 1 RGB slide).
> 
> Great! Let's briefly go through all optional parameters and double-check whether they should indeed be optional. For example, the `selectedSeriesInstanceUID` property on the `Slide` class is optional, but the application won't function properly if that property is not set. Same applies to `containerIdentifier`, which represents a type 1 DICOM attribute that is guaranteed to be present in any VL Whole Sllide Microscopy Image instance. If the value cannot be determined upon construction of the `Slide` object, the application should just fail immediately and gracefully, rather than propagating the issue through the app.

Done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/3a14700fadc8dd2ec993d897362a0af8e0770b06

2021-07-26 09:49 UTC, Punzo commented
Commit https://github.com/MGHComputationalPathology/slim/pull/25/commits/25667f8eead3b4bc2bf2cee630a5f9e1fd65cb0b implement first step of https://github.com/MGHComputationalPathology/slim/issues/38

2021-07-26 10:00 UTC, Punzo commented
This PR has been tested both with OpenLayer versions 6.5.0 and 6.6.1. See also https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/pull/57

2021-07-28 20:16 UTC, hackermd requested changes
Thanks for the changes @Punzo. Already looks much cleaner. There are still a couple of things I suggest changing regarding the implementation of `createSlides()`. This method has become a critical piece that determines a lot of the downstream application logic. Therefore,  this part needs to be rock solid.

2021-07-28 20:16 UTC, hackermd commented on src/data/slides.tsx
> +  _addOverviewInstanceMetadata(slideOptionsItem, instancesMetadata.overviewMetadata)
The logic of these methods is really hard to understand and error prone in my opinion.

I don't like the fact that the `SlideOptions` object is first created with invalid default values (e.g., empty strings for identifiers) and then passed around for its properties to be populated by different methods.

I would generally avoid functions/methods with side effects whenever possible and I would instead suggest first collecting the relevant information via dedicated methods and then creating the `SlideObject` object.

The `_addLabelInstanceMetadata()` and `_addOverviewInstanceMetadata()` methods basically just filter the metadata. This could probably be directly handled via [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) using `_doesInstanceBelongToSlide()`.

The `addVolumeInstanceMetadata()` method currently does more than just filtering, but I feel that this could be handled separately, i.e., the metadata could be filtered first and the other attributes could be determined afterwards.

I feel this approach would be much more intuitive and avoid all of the `=== undefined` and `=== ''` checks.

2021-07-28 20:16 UTC, hackermd commented on src/data/slides.tsx
> +  volumeMetadataList: object[]
In general, I would avoid using terms such as `list` and `array` in variable/property/key names. The type annotation already clearly indicates whether the value represents a single item or an array of items.

2021-07-28 20:16 UTC, hackermd commented on src/data/slides.tsx
> +): dmv.metadata.VLWholeSlideMicroscopyImage | undefined {
Do we allow `Slide` objects without any VOLUME image instances? If not, I would also avoid `undefined` here. This should no longer be necessary after the suggested refactoring (see above comment).

2021-08-04 21:16 UTC, hackermd commented on src/components/SamplesList.tsx
> +        <h4 />
That is causing linting issues.

```suggestion
```

2021-08-04 21:37 UTC, hackermd commented on src/components/SampleItem.tsx
> +    )
```suggestion
    const removeSampleButton = (
      <CloseCircleOutlined
          style={{ color: '#FF0000' }}
          onClick={this.handleRemoveSample}
      />
    )

    return (
      <Space align='start'>
        <div style={{ paddingLeft: '14px', paddingTop: '10px' }}>
          <Space direction='vertical' align='end' size={100}>
            <Space direction='vertical' align='end'>
              <Switch
                size='small'
                checked={this.state.visible}
                onChange={this.handleVisibilityChange}
                checkedChildren={<FaEye />}
                unCheckedChildren={<FaEyeSlash />}
              />

              <Popover placement='left' content={content} title='Blending Parameters'>
                <Button type='primary' shape='circle' icon={<SettingOutlined />} />
              </Popover>
            </Space>
          </Space>
        </div>
        <Space direction='horizontal' align='start'>
          <Badge count={removeSampleButton} title='Remove sample'>
            <Description
              header={'ID: ' + identifier}
              attributes={attributes}
              selectable
              hasLongValues
            />
          </Badge>
        </Space>
      </Space>
    )
```

2021-08-05 10:53 UTC, Punzo commented on src/data/slides.tsx
> +}
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/d0c0cb45e4197f19a031b1eb5fd19c5b56173f09

2021-08-05 10:53 UTC, Punzo commented on src/data/slides.tsx
> +  ) as dmv.metadata.VLWholeSlideMicroscopyImage
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/2356fa22fd5253f4d394d2d804f12127170c224c

2021-08-05 10:53 UTC, Punzo commented on src/data/slides.tsx
> +    ) as dmv.metadata.VLWholeSlideMicroscopyImage
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/2356fa22fd5253f4d394d2d804f12127170c224c

2021-08-05 10:54 UTC, Punzo commented on src/data/slides.tsx
> +    } else if (instanceIsMonochorme !== slideOptionsItem.areImagesMonochrome) {
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/1d864a753f78c5093c37e15c4c3cca57fe75f0b3

2021-08-05 10:56 UTC, Punzo commented on src/data/slides.tsx
> +  volumeMetadataList: object[]
fixed in https://github.com/MGHComputationalPathology/slim/pull/25/commits/e3e5948bcfffe2ac2e784c8212f07e3083e571c4

2021-08-05 11:23 UTC, Punzo commented on src/components/SampleItem.tsx
> +    )
fixed in https://github.com/MGHComputationalPathology/slim/pull/25/commits/47c955fe1c0fac571edc07c57bc835473d236275

2021-08-05 11:23 UTC, Punzo commented on src/components/SamplesList.tsx
> +        <h4 />
fixed in https://github.com/MGHComputationalPathology/slim/pull/25/commits/47c955fe1c0fac571edc07c57bc835473d236275

2021-08-05 11:23 UTC, Punzo commented on src/components/SamplesList.tsx
> +    })
https://github.com/MGHComputationalPathology/slim/pull/25/commits/47c955fe1c0fac571edc07c57bc835473d236275

2021-08-05 13:23 UTC, Punzo commented on src/data/slides.tsx
> +  _addOverviewInstanceMetadata(slideOptionsItem, instancesMetadata.overviewMetadata)
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/556a73606532c161180c101a812f644c6f809723

2021-08-05 13:23 UTC, Punzo commented on src/data/slides.tsx
> +): dmv.metadata.VLWholeSlideMicroscopyImage | undefined {
done in https://github.com/MGHComputationalPathology/slim/pull/25/commits/556a73606532c161180c101a812f644c6f809723

2021-08-05 13:24 UTC, Punzo commented
> Thanks for the changes @Punzo. Already looks much cleaner. There are still a couple of things I suggest changing regarding the implementation of `createSlides()`. This method has become a critical piece that determines a lot of the downstream application logic. Therefore, this part needs to be rock solid.

Hi @hackermd, thansk for the review, I have applied the comments!

2021-08-09 16:11 UTC, merged

2021-08-09 16:12 UTC, hackermd commented
Thank you @Punzo. I have merged the PR into a separate `dev` branch, where I will perform additional tests before finally merging everything into `master`.