Add retry and custom error messages
MGHComputationalPathology/slim pull request #53
Opened 2021-08-10 19:48 UTC by igoroctaviano

- Original issue: #37 

### Usage
```
window.config = {
  path: "/",
  /** This is an array, but we'll only use the first entry for now */
  servers: [
    {
      id: "local",
      url: "https://idc-external-006.uc.r.appspot.com",
      write: true,
      retryOptions: {
        retries: 5,
        factor: 3,
        minTimeout: 1 * 1000,
        maxTimeout: 60 * 1000,
        randomize: true,
        retryableStatusCodes: [429, 500],
      },
      errorMessages: [
        { status: 429, message: 'Failed 429!', redirect: 'https://google.com' },
        { status: 404, message: 'Failed 404!' }
      ]
    }
  ],
```

2021-08-10 21:05 UTC, hackermd requested changes
Very nice!!! I have a few minor stylistic comments, but also some comments related to changes to be introduced via #52 that we should discuss further.

2021-08-10 21:05 UTC, hackermd commented on src/utils/xhrRetryHook.ts
> + * @returns {function} the configured retry request function
Two things:

* I am trying to standardize docstrings to use the `@param options.name - Description` pattern:
  - no types to void typos (types are already annotated via Typescript)
  - a `-` in between parameter name and description
  - Capitalize first word of description
* Some of the parameters are really hard to understand and the description could be further clarified 

```suggestion
 * @param options
 * @param options.retries - Number of retries
 * @param options.factor - Factor
 * @param options.minTimeout - Min number of seconds to wait before next retry
 * @param options.maxTimeout - Max number of seconds to wait before next retry
 * @param options.randomize - Whether randomization should be applied
 * @param options.retryableStatusCodes - HTTP status codes that can trigger a retry
 * @returns Configured retry request function
```

2021-08-10 21:05 UTC, hackermd commented on src/utils/xhrRetryHook.ts
> + * @returns {XMLHttpRequest} request instance optionally modified
```suggestion
 * @param request - XHR request instance
 * @param metadata - Metadata about the request
 * @returns XHR request instance (potentially modified)
```

2021-08-10 21:11 UTC, hackermd requested changes

2021-08-10 21:11 UTC, hackermd commented on src/App.tsx
> +            window.location.href = redirect
Not sure that's a good idea. We have been having issues with redirects with OIDC..

2021-08-10 21:11 UTC, hackermd commented on src/App.tsx
> +        <InfoPage type="error" message={this.state.error.message} />
@igoroctaviano I just merged #52. Could you kindly rebase and see whether this will need (may benefit from) modification? There are other kinds of errors (authentication failed, etc.) that could be handled more elegantly with this new approach.

2021-08-10 21:24 UTC, igoroctaviano commented on src/App.tsx
> +            window.location.href = redirect
Any suggestion on how we might do this without OIDC related issues?

2021-08-10 21:46 UTC, igoroctaviano commented on src/App.tsx
> +    const onError = (error: ServerErrorMessage, serverSettings: ServerSettings) => {
Done, thanks.

2021-08-10 21:46 UTC, igoroctaviano commented on src/App.tsx
> +        onError: onError.bind(this)
Removed, thanks.

2021-08-10 21:47 UTC, igoroctaviano commented on src/App.tsx
> +        <InfoPage type="error" message={this.state.error.message} />
Done!

2021-08-10 21:47 UTC, igoroctaviano commented on src/AppConfig.d.ts
> +export interface ServerErrorMessage {
Yes, updated.

2021-08-10 21:47 UTC, igoroctaviano commented on src/AppConfig.d.ts
> +  errorMessages: ServerErrorMessage[]
Done.

2021-08-10 21:47 UTC, igoroctaviano commented on src/DicomWebManager.tsx
> +  private onError: Function
Done.

2021-08-10 21:47 UTC, igoroctaviano commented on src/DicomWebManager.tsx
> +    onError?: Function
Done.

2021-08-10 21:47 UTC, igoroctaviano commented on src/DicomWebManager.tsx
> +    this.onError = onError || noop;
Updated, thanks.

2021-08-10 21:47 UTC, igoroctaviano commented on src/components/InfoPage.tsx
> +  const onClickHandler = () => window.location.href = '/';
Removed, let's make it a dead-end for now, and later we can add custom buttons if needed.

2021-08-10 21:48 UTC, igoroctaviano commented on src/utils/xhrRetryHook.ts
> + * @returns {function} the configured retry request function
Updated, thanks.

2021-08-10 21:48 UTC, igoroctaviano commented on src/utils/xhrRetryHook.ts
> + * @returns {XMLHttpRequest} request instance optionally modified
Updated, thanks.

2021-08-10 21:50 UTC, igoroctaviano commented
@hackermd Thanks for the review. Just pushed the requested changes but we still need to cover the redirect flow which you think we might have a problem with using the window call. This is the last remaining bit to get done :)

2021-08-10 22:02 UTC, hackermd commented on src/App.tsx
> +            window.location.href = redirect
Maybe [Redirect](https://reactrouter.com/web/api/Redirect)? There is an [example auth workflow](https://reactrouter.com/web/example/auth-workflow), which may also apply to this situation.

2021-08-10 22:07 UTC, hackermd commented on src/App.tsx
> +            window.location.href = redirect
Although this may require a different approach..

2021-08-10 22:14 UTC, igoroctaviano commented on src/App.tsx
> +            window.location.href = redirect
Redirect only works if its the same domain

2021-08-10 22:25 UTC, hackermd commented on src/App.tsx
> +            window.location.href = redirect
I just implemented the approach for auth via f81a8f425f705380dec85d34b6597c8a2f494186. We may be able to further modify this to satisfy the need of this issue.

2021-08-10 22:30 UTC, igoroctaviano commented on src/App.tsx
> +            window.location.href = redirect
This example is still considering the same domain which might not be the case here. What we want is a way to define a totally different URL in the redirect property and if the condition applies (status code === 404) the viewer should redirect the user to this new site.

I might be out of the loop on the OIDC issues though, can you give me some context then I can try to find workarounds to this problem?

2021-08-10 22:35 UTC, hackermd commented on src/App.tsx
> +            window.location.href = redirect
Sent PR #54 your way targeting this branch.

2021-08-10 22:38 UTC, hackermd commented on src/App.tsx
> +            window.location.href = redirect
> This example is still considering the same domain which might not be the case here. What we want is a way to define a totally different URL in the redirect property and if the condition applies (status code === 404) the viewer should redirect the user to this new site.

Sorry, I misunderstood. Do we really want to redirect to a completely different web site? I would probably prefer to redirect to a route within the app.

2021-08-10 22:42 UTC, igoroctaviano commented on src/App.tsx
> +            window.location.href = redirect
@hackermd I'm gathering requirements from this issue: https://github.com/MGHComputationalPathology/slim/issues/37
Maybe Bill just wants to have a custom message being displayed in case of an error occurs, no need to redirect then?

2021-08-10 22:48 UTC, hackermd commented on src/App.tsx
> +            window.location.href = redirect
I completely misunderstood the intention of this feature. I would prefer not redirecting to another web site and just redirecting the user to an error "page" within the app that displays the error message to the user. A link to another web site could be embedded in the error message and the user can follow the link by clicking on it. What do you think?

2021-08-10 22:51 UTC, hackermd commented on src/App.tsx
> +            window.location.href = redirect
@wlongabaugh what are your thoughts? Would an error message (potentially including a link) be sufficient?

The message could look something like:

```html
Quota exceeded. For more information please read <a href="https://portal.example.com/quotaExceeded.html">this</a>. 
```

2021-08-10 23:06 UTC, wlongabaugh commented on src/App.tsx
> +            window.location.href = redirect
Sure, that works okay, certainly in the short term.

2021-08-11 18:10 UTC, hackermd commented on src/AppConfig.d.ts
> +  errorMessages: ErrorMessageSettings[]
I would make these optional

```suggestion
  retry?: RetryRequestSettings
  errorMessages?: ErrorMessageSettings[]
```

2021-08-11 18:15 UTC, hackermd commented on src/DicomWebManager.tsx
> +      this.onError = onError;
```suggestion
      this.handleError = onError;
```

2021-08-11 18:19 UTC, hackermd commented on src/utils/xhrRetryHook.ts
> +export interface RetryOptions {
See corresponding comment in `AppConfig.d.ts`

2021-08-11 18:34 UTC, hackermd commented on src/utils/xhrRetryHook.ts
> +  }
Since the options object is obtained from the configuration file, we should probably guard against all eventualities.

2021-08-11 20:27 UTC, hackermd requested changes
Excellent! Thank you @igoroctaviano. I have only one remaining comment. I would prefer all settings to be defined in `AppConfig.d.ts` and potentially imported from there in a module rather than the other way around.

2021-08-11 20:27 UTC, hackermd commented on public/config/local.js
> +      url: "https://idc-external-006.uc.r.appspot.com",
Please don't change the `local.js` file.

2021-08-11 20:27 UTC, hackermd commented on src/AppConfig.d.ts
> +import { RetryRequestSettings } from './utils/xhrRetryHook';
Please define the setting here in `AppConfig.d.ts` rather than in `utils/xhrRetryHook`.

2021-08-11 20:30 UTC, igoroctaviano commented on public/config/local.js
> +      url: "https://idc-external-006.uc.r.appspot.com",
@hackermd ill let you know when i'm finish pushing changes

2021-08-11 20:41 UTC, igoroctaviano commented
@hackermd I think I'm done with the changes. Can you give it another look? Thanks in advance

2021-08-11 21:17 UTC, hackermd approved these changes

2021-08-11 21:17 UTC, merged